### ISSUE TITLE
Add a background for scholarships and jobs section under the Resources page

### ISSUE THREAD

**Issue by KushalBhanot** [KushalBhanot/Techify#10]
Use your creativity and make the Resources page more lively. I'm looking for a slight improvement in the UI of the Resources page.

**Comment by MaximeKoitsalu** [comment]
Hey @KushalBhanot, I can take up this task :)

**Comment by KushalBhanot** [comment]
Sure, @MaximeKoitsalu! Go ahead. I'm assigning it to you 👍🏻

**Comment by MaximeKoitsalu** [comment]
@KushalBhanot Created a pull request! If you need any more help, I gladly help
