### ISSUE TITLE
Fix navlinks across the HTML pages by adding corresponding href links

### ISSUE THREAD

**Issue by KushalBhanot** [KushalBhanot/Techify#11]
This is a very beginner-friendly issue. Meant only for first-timers.

**Comment by Priya19999** [comment]
Can I please work on this issue?

**Comment by ShobhitRathi** [comment]
can i work on this? familiar with frontend dev

**Comment by lukes-code** [comment]
submitted merge 'Link btn fix #12'

**Comment by KushalBhanot** [comment]
Sure, folks! Go ahead @Priya19999, @ShobhitRathi and @lukes-code. I'll merge the first valid PR.

**Comment by ShobhitRathi** [comment]
which page / url / section you want us to link it with?

**Comment by Priya19999** [comment]
Can you please provide me detail of what we have to link the buttons with? The ideas and Products button is not responding what should I link them with?
