### ISSUE TITLE
Fix the login button on index.html

### ISSUE THREAD

**Issue by KushalBhanot** [KushalBhanot/Techify#6]
The page shakes when hovering over the login button. Make sure to test your PR before making one.

**Comment by KushalBhanot** [comment]
Make the PR under the `develop` branch.

**Comment by 20Koen02** [comment]
I will take this. Can you assign me?

**Comment by Atimabh** [comment]
I have made a PR. please review it. #7

**Comment by 20Koen02** [comment]
Nevermind :) some asshole stole it 
cough @Atimabh
